// napiš program, co naačte dvě čísla a vypíše jejich součet, rozdíl, součin a podíl a další matematické operace
Console.WriteLine("Zadejte první číslo:");
double num1 = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Zadejte druhé číslo:");
double num2 = Convert.ToDouble(Console.ReadLine());
double sum = num1 + num2;
double difference = num1 - num2;
double product = num1 * num2;
double quotient = num1 / num2;
double power = Math.Pow(num1, num2);
double sqrtNum1 = Math.Sqrt(num1);
double sqrtNum2 = Math.Sqrt(num2);
Console.WriteLine($"Součet: {sum}");
Console.WriteLine($"Rozdíl: {difference}");
Console.WriteLine($"Součin: {product}");
Console.WriteLine($"Podíl: {quotient}");
Console.WriteLine($"Mocnina (num1^num2): {power}");
Console.WriteLine($"Druhá odmocnina z prvního čísla: {sqrtNum1}");
Console.WriteLine($"Druhá odmocnina z druhého čísla: {sqrtNum2}");
Console.WriteLine($"Absolutní hodnota prvního čísla: {Math.Abs(num1)}");
Console.WriteLine($"Absolutní hodnota druhého čísla: {Math.Abs(num2)}");
Console.WriteLine($"Sinus prvního čísla: {Math.Sin(num1)}");
Console.WriteLine($"Sinus druhého čísla: {Math.Sin(num2)}");
Console.WriteLine($"Cosinus prvního čísla: {Math.Cos(num1)}");
Console.WriteLine($"Cosinus druhého čísla: {Math.Cos(num2)}");
Console.WriteLine($"Tangens prvního čísla: {Math.Tan(num1)}");
Console.WriteLine($"Tangens druhého čísla: {Math.Tan(num2)}");
Console.WriteLine($"Logaritmus prvního čísla: {Math.Log(num1)}");
Console.WriteLine($"Logaritmus druhého čísla: {Math.Log(num2)}");
